### ISSUE TITLE
[Install in powershell] cannot install in win10

### ISSUE THREAD

**Issue by hurrine** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#137]
**Gateway Version**: <Build number>
**Extension Version** that's been used if it applies

**To Reproduce**
1. Download WindowsAdminCenter2110
2. Install in powershell as admin, execute: msiexec /i WindowsAdminCenter2110.msi DEV_MODE=1
3. Get error:

![image](https://user-images.githubusercontent.com/24801810/157020031-9e2468a0-7303-430d-beb8-24024381c0f2.png)

log: 
Exception: 
System.Management.Automation.CmdletProviderInvocationException
Access is denied.  
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1(T0 arg0)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ManagementExperience.Setup.CustomActions.PowerShellActions.<Execute>d__18.MoveNext()
MSI (s) (EC!CC) [18:04:48:301]: Product: Windows Admin Center -- Unhandled Exception: System.Management.Automation.CmdletProviderInvocationException Access is denied. 

**Expected behavior**
Any action can be done to solve it? 
**Screenshots & Additional context**

**Comment by RebeccaMbulaMs** [comment]
Hello!
My name is Rebecca and I'm a Product Manager on WAC.
I'm sorry that you experienced this issue - Is it still happening?
If so, are you available to schedule a troubleshooting call? 
If yes, please send me your time zone and availability to rwambua@microsoft.com
Kind regards!
