### ISSUE TITLE
SmeDesktop unable to connect to any device for Admin, error 500 bad format, Exception from HRESULT: 0x8007000B

### ISSUE THREAD

**Issue by TechTrev** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#258]
**Gateway Version**: 2110.2
**Extension Version**: N/A

**To Reproduce**
1. Install windows admin center on windows 10 21H2 (including latest patches)
2. Launch Windows Admin Center
3. Select any device to open for remote management.  (pre-installed localhost for example)
4. Connection error observed
**Connection error**
An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
5. Event Log entry related to connection error
<pre><code>500 - BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
 Stack trace:    at System.Net.UnsafeNclNativeMethods.HttpApi.GetChunks(Byte[] memoryBlob, IntPtr originalAddress, Int32& dataChunkIndex, UInt32& dataChunkOffset, Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.HttpRequestStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.Owin.Host.HttpListener.RequestProcessing.ExceptionFilterStream.<ReadAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Net.Http.StreamToStreamCopy.<CopyAsyncToPreSizedLimitMemoryStream>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<LoadIntoBufferAsyncCore>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpContent.<WaitAndReturnAsync>d__63`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ManagementExperience.Common.PowerShell.PowerShellRequest.<Parse>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ManagementExperience.FrontEnd.Controllers.FeatureController.<InvokeCommand>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ManagementExperience.FrontEnd.Handlers.ImpersonationActionInvoker.<InvokeActionAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
</code></pre>

**Expected behavior**
Device management screen loads

**Screenshots & Additional context**
![image](https://user-images.githubusercontent.com/117054976/198925101-57b8452d-6a43-4e26-a738-a7569e6435d0.png)
-- target install laptop has several network interfaces both virtual (VMware and Virtualbox), ethernet and wifi.
-- Various development software installed on impacted machine VS2013 and Android Studio

**Things Investigated/Tried Already**
-- Downloaded msi when installed on another windows 10 machine does not experience the same problem. Appears to only impacts this specific laptop.
-- Remove and re-install does not appear to help.

**Additional Note**
Happy to provide any and all additional detail.

**Comment by RebeccaMbulaMs** [comment]
Hi, 
I'm Rebecca, PM on WAC. Are you still facing this issue?
I'd be happy to troubleshoot with you. If this is OK with you, please send me an email on (rwambua@microsoft.com) with your timezone and I will set up a teams call.
Kind regards.

**Comment by yanuoma** [comment]
Thanks for the original report, @TechTrev, and apologies for the long delay in our triage cycle.

We've reviewed this against the current Windows Admin Center platform and believe the underlying behavior has been addressed. The product has evolved significantly since this report was filed.

If you can still reproduce this on a current WAC build, please reply here and we'll reopen with a fresh investigation — sharing your current Gateway build number and a short repro would help us a lot.

Thanks again for taking the time to write this up. 🙏

— The Windows Admin Center team
