### ISSUE TITLE
WAC stopped connecting to machines via WinRM over the past week

### ISSUE THREAD

**Issue by aggietallboy** [MicrosoftDocs/Windows-Admin-Center-Ideas-and-Feedback#281]
Last week I installed the 2211 update for WAC.
I tested connectivity to ~5 of our machines, and was pretty satisfied.
Now I can connect to nothing.

400 - PSRemotingTransportException: Connecting to remote server myserver.fqdn failed with the following error message : WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet. For more information, see the about_Remote_Troubleshooting Help topic.
 Stack trace:    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
   at System.Management.Automation.RemoteRunspace.Open()
   at Microsoft.ManagementExperience.PowerShell.PowerShellOperations.<>c__DisplayClass9_0.<Invoke>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ManagementExperience.PowerShell.PowerShellApi.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ManagementExperience.FrontEnd.Controllers.FeatureController.<InvokeCommand>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ManagementExperience.FrontEnd.Handlers.ImpersonationActionInvoker.<InvokeActionAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()

But from powershell on the WAC gateway machine:

PS C:\Windows\system32> test-wsman myserver.fqdn

wsmid           : http://schemas.dmtf.org/wbem/wsman/identity/1/wsmanidentity.xsd
ProtocolVersion : http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd
ProductVendor   : Microsoft Corporation
ProductVersion  : OS: 0.0.0 SP: 0.0 Stack: 3.0

A-OK right?

Same behavior with windows login and with "manage as"
Same behavior from local machine where WAC is installed and from remote machine calling WAC.

ONLY machine I seem to be able to connect to right now is the WAC machine itself¿and even that is only when run locally.

I've reinstalled WAC, to no avail

Also confirmed connectivity to targeţmyserver.fqdn by adding to Server Manager -- everything populated as expected.

Server OS - Server 2022 Datacenter 20348.1366
Hyper-V VM 4 vCPU (Xeon E5-2667 v4)
16 GB RAM

Windows Admin Center 2211

MS Edge on local WAC console server
Chrome on remote connection

Tested regular and incognito

**Comment by aggietallboy** [comment]
I can connect to the WAC gateway machine from other machines

**Comment by aggietallboy** [comment]
DOH
It was me... i flagged use SSL for WinRM.
Undid the registry setting and lo and behold and we can connect again.

**Comment by aggietallboy** [comment]
https://techcommunity.microsoft.com/t5/windows-admin-center/windows-admin-center-revert-quot-use-winrm-over-https-only-quot/m-p/1585108
